name: iOS Ad-Hoc IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install signing assets
        shell: bash
        run: |
          SECURITY_KEYCHAIN=build.keychain
          CERT_PATH=cert.p12
          PROFILE_DIR=~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_PATH=$PROFILE_DIR/profile.mobileprovision

          mkdir -p "$PROFILE_DIR"
          echo "$IOS_CERT_P12_BASE64" | base64 --decode > "$CERT_PATH"
          echo "$IOS_MOBILEPROVISION_BASE64" | base64 --decode > "$PROFILE_PATH"

          security create-keychain -p "" "$SECURITY_KEYCHAIN"
          security default-keychain -s "$SECURITY_KEYCHAIN"
          security unlock-keychain -p "" "$SECURITY_KEYCHAIN"
          security import "$CERT_PATH" -P "$IOS_CERT_P12_PASSWORD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$SECURITY_KEYCHAIN"

      - name: Archive
        run: |
          SCHEME="$(xcodebuild -list -json | plutil -extract project.schemes json -o - - | /usr/bin/python3 -c 'import sys,json; print(json.load(sys.stdin)[0])' 2>/dev/null || echo YourAppScheme)"
          xcodebuild \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/App.xcarchive \
            clean archive

      - name: Create ExportOptions.plist
        run: |
          cat > ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>ad-hoc</string>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>manual</string>
            <key>stripSwiftSymbols</key><true/>
            <key>destination</key><string>export</string>
            <key>thinning</key><string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build/export \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: App-IPA
          path: build/export/*.ipa
